## This is test deployment for Kubernetes platforms.
## This is _not_ intended to be use in producction.
##
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: test-service-catalog
  name: test-service-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-service-catalog
  template:
    metadata:
      labels:
        app: test-service-catalog
    spec:
      containers:
      - image: bitnami/service-catalog
        name: service-catalog
